---
namespace: pagerduty
name: pagerduty
version: 0.2.0
readme: README.md
authors:
  - Steve Fulmer (@stevefulme1)
description: Ansible collection for the PagerDuty API
license:
  - GPL-3.0-or-later
tags:
  - pagerduty
  - api
  - monitoring
repository: https://github.com/stevefulme1/pagerduty.pagerduty
build_ignore:
  - tests/output
  - .tox
  - .venv
license_file: COPYING
