---
notesdir: fragments
changes_file: changelog.yaml
changes_format: combined
keep_fragments: false
changelog_filename_template: CHANGELOG.rst
changelog_filename_version_depth: 0
mention_ancestor: true
trivial_section_name: trivial
title: pagerduty.pagerduty
sections:
  - - major_changes
    - Major Changes
  - - minor_changes
    - Minor Changes
  - - breaking_changes
    - Breaking Changes / Porting Guide
  - - deprecated_features
    - Deprecated Features
  - - removed_features
    - Removed Features (previously deprecated)
  - - security_fixes
    - Security Fixes
  - - bugfixes
    - Bugfixes
  - - known_issues
    - Known Issues
  - - new_modules
    - New Modules
  - - new_plugins
    - New Plugins
