---
changelog_filename_version_depth: 0
changes_file: changelog.yaml
changes_format: combined
keep_fragments: false
notes_dir: fragments
sanitize_changelog: true
title: "pagerduty.pagerduty Release Notes"
trivial_section_name: trivial
use_fqcn: true
